"""Generate the per-feature leakage table for the forecasting docs.

    uv run python docs/generate_feature_catalogue.py

Section 4 of the Step 6 brief asks for a table of
``feature_name / definition / available_at_time / leakage_risk``.

``leakage_risk`` is **derived, never hand-entered.** Two reasons. A hand-written
risk column duplicates information the ``Temporality`` already carries, and
duplicated facts drift - the day someone changes a feature's temporality without
remembering to change its risk rating, the table starts lying. And adding a
``leakage_risk`` field to ``FeatureSpec`` would need populating across 100+
specs, most of which would say the same thing.

The derivation encodes the actual rule the platform enforces:

* ``BACKWARD`` - computed from history strictly before the row's date. Safe by
  construction, because every temporal feature routes through ``shifted_group``
  or ``rolling_on_shifted``.
* ``CONTEMPORANEOUS`` - same-date. Safe at the *origin* of a forecast, unsafe if
  read at the target date, so the risk depends on which side it lands.
* ``FORWARD_PLANNED`` - deliberately reads forward. Legitimate only because the
  source table is ``KNOWN_IN_ADVANCE``, and each one carries a written
  justification that the config validator cross-checks.
"""

from __future__ import annotations

from pathlib import Path

from features.contracts.catalogue import FEATURE_SPECS
from features.contracts.specs import Temporality
from ml.baseline.training import EXCLUDED_FROM_FEATURES, SUPPLY_FEATURES
from ml.forecasting.dataset import _ORIGIN_CALENDAR_NOISE, FORECAST_EXCLUDED

OUTPUT = Path(__file__).parent / "forecasting" / "feature_catalogue.md"

#: Families whose target-date copy is used by the forecaster, carrying an `h_`
#: prefix. Everything else is read at the origin.
_TARGET_SIDE_GROUPS = {"temporal", "promotion"}


def availability(spec) -> str:
    """When the value is knowable, in forecasting terms."""
    if spec.temporality is Temporality.FORWARD_PLANNED:
        return "target date (planned)"
    if spec.group.value in _TARGET_SIDE_GROUPS:
        return "target date `t+h`"
    return "origin `t`"


def leakage_risk(spec) -> tuple[str, str]:
    """Derived risk rating and the reason for it."""
    name = spec.name

    if name in EXCLUDED_FROM_FEATURES or name in FORECAST_EXCLUDED:
        return "EXCLUDED", "target-derived or non-reproducible at serve time"
    if name in SUPPLY_FEATURES:
        return "EXCLUDED", "supply signal - the model would learn censoring as demand"
    if name in _ORIGIN_CALENDAR_NOISE:
        return "none", "origin-side copy dropped; the `h_` target-date copy is used"

    if spec.temporality is Temporality.FORWARD_PLANNED:
        return "managed", (spec.forward_justification or "known-in-advance table")
    if spec.temporality is Temporality.CONTEMPORANEOUS:
        if spec.group.value in _TARGET_SIDE_GROUPS:
            return "none", "target date is what is being forecast; source is KNOWN_IN_ADVANCE"
        return "low", "same-date value, read at the origin only"
    return "none", "computed from history strictly before the row's date"


def render() -> str:
    lines = [
        "# Forecasting feature catalogue",
        "",
        "> Generated by `docs/generate_feature_catalogue.py`. Do not edit by hand.",
        "",
        "Every feature the forecasting model can see, with **when its value becomes "
        "knowable** and **what leakage risk it carries**. The risk column is derived "
        "from the feature's declared temporality plus the forecaster's own exclusion "
        "lists - it is not a separate hand-maintained judgement, because a duplicated "
        "fact drifts.",
        "",
        "## How to read the columns",
        "",
        "| Column | Meaning |",
        "|---|---|",
        "| **available at** | `origin t` - knowable when the forecast is made. "
        "`target date t+h` - the day being forecast, legitimate only for "
        "`KNOWN_IN_ADVANCE` tables. |",
        "| **risk** | `none` safe by construction; `low` same-date but origin-only; "
        "`managed` reads forward with a written justification; `EXCLUDED` never "
        "reaches the model. |",
        "",
        "## Why some features are excluded outright",
        "",
        "| Exclusion | Reason |",
        "|---|---|",
        "| target-derived (`revenue`, `cost`, `gross_profit`) | `revenue = units x price` "
        "recovers the target exactly |",
        "| supply (`inventory_*`, `stockout_*`) | Step 4 measured it: with inventory "
        "features the model recovered only 0.30 of true stockout demand, having learned "
        "that low stock predicts low sales |",
        "| `time_index` | anchored to the frame's own minimum, so the same calendar date "
        "differs between training and serving |",
        "| `year`, `financial_year` | either a year the model has seen and overfits, or "
        "one it cannot place |",
        "| `part` | hive partition key - a storage artifact that does not exist for a "
        "future date |",
        "",
    ]

    by_group: dict[str, list] = {}
    for spec in FEATURE_SPECS.values():
        by_group.setdefault(spec.group.value, []).append(spec)

    for group in sorted(by_group):
        specs = sorted(by_group[group], key=lambda s: s.name)
        lines += [
            f"## {group}",
            "",
            "| feature | definition | available at | risk | why |",
            "|---|---|---|---|---|",
        ]
        for spec in specs:
            risk, reason = leakage_risk(spec)
            definition = spec.description.replace("|", "/").strip()
            if spec.transformation:
                definition += f" ({spec.transformation.replace('|', '/')})"
            lines.append(
                f"| `{spec.name}` | {definition} | {availability(spec)} | "
                f"**{risk}** | {reason} |"
            )
        lines.append("")

    excluded = sorted(SUPPLY_FEATURES | FORECAST_EXCLUDED)
    lines += [
        "## Never features",
        "",
        "Columns present in the panel that are removed before the model sees anything:",
        "",
        "```",
        "\n".join(f"  {name}" for name in excluded if not name.startswith("_")),
        "```",
        "",
        "## Verification",
        "",
        "These are not documentation-only claims. `tests/forecasting/test_dataset.py` "
        "asserts that no supply feature, no target-derived column, no `time_index` and "
        "no hive partition key reaches the feature set, and "
        "`tests/forecasting/test_leakage.py` corrupts all `OBSERVED` data after a cutoff "
        "and asserts the training features are byte-identical.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Written {OUTPUT} ({len(FEATURE_SPECS)} features)")


if __name__ == "__main__":
    main()
